const fs=require('node:fs/promises'),path=require('node:path'),assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const root=path.resolve(__dirname,'../public');
(async()=>{const browser=await chromium.launch({...(process.env.CHROMIUM_PATH?{executablePath:process.env.CHROMIUM_PATH}:{}),args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});
const files=await fs.readdir(root+'/js');const sources=await Promise.all(files.filter(f=>f.endsWith('.js')).map(f=>fs.readFile(root+'/js/'+f,'utf8')));
const exports=new Set();for(const s of sources)for(const m of s.matchAll(/import\s*\{([^}]+)\}\s*from\s*["']https:\/\/www.gstatic.com[^"']+["']/g))for(const n of m[1].split(','))exports.add(n.trim());
const mocks={collection:'(db,name)=>({name})',doc:'(db,name,id)=>({name,id})',query:'ref=>ref',onSnapshot:'(ref,cb)=>{(window.listeners[ref.name]??=[]).push(cb);cb(window.snapshot(ref.name));return ()=>{};}',getDocs:'async ref=>window.snapshot(ref.name)',getDoc:'async()=>({exists:()=>true,data:()=>({status:"Active",accessLevel:"Admin",role:"Mechanic",displayName:"Test User",employeeNumber:"123"})})',onAuthStateChanged:'(auth,cb)=>{setTimeout(()=>cb(auth.currentUser),0);return ()=>{};}',serverTimestamp:'()=>null',writeBatch:'()=>({set(){},update(){},commit:async()=>{}})',arrayUnion:'(...values)=>values',httpsCallable:'()=>async()=>({data:{}})'};
const mock=Array.from(exports).map(n=>`export const ${n}=${mocks[n]||'()=>({})'};`).join('\n');
const dbSource=await fs.readFile(root+'/js/db.js','utf8');const dbNames=[...dbSource.matchAll(/export (?:async )?function (\w+)/g)].map(m=>m[1]);
const mockDb=dbNames.map(n=>`export const ${n}=${n==='getEmployeeByEmail'?'async()=>({status:"Active",accessLevel:"Admin",role:"Mechanic",displayName:"Test User",employeeNumber:"123"})':n.startsWith('listen')?'cb=>{if(typeof cb==="function")cb([]);return ()=>{};}':'async()=>[]'};`).join('\n');
for(const html of ['workshop.html','mechanic.html']){
const page=await browser.newPage({timezoneId:'Australia/Sydney'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.addInitScript(()=>{window.listeners={};window.seeds={buses:[{id:'bus1',fleetNumber:'M09104',status:'Active',depot:'Punchbowl',fuelType:'Diesel',regoExpiryDate:'2027-08-01',next90DaySafetyCheckDate:'2026-10-27',nextFireSuppressionCheckDate:'2026-10-20'}],workshopJobs:[{id:'job1',jobNumber:'WJ-2026-001',busId:'bus1',fleetNumber:'M09104',jobType:'Repair',status:'Assigned',assignedMechanic:'Test User',assignedMechanicName:'Test User',assignedMechanicEmployeeNumber:'123',createdAt:'2026-10-01T08:00:00Z'},{id:'job2',jobNumber:'WJ-2026-002',busId:'bus1',fleetNumber:'M09104',jobType:'90 Day Safety Check',status:'Closed',createdAt:'2026-10-01T08:00:00Z',inspectionCompletedDate:'2026-10-01',last90DaySafetyCheckJobId:'job2'}],employees:[]};window.seeds.buses[0].last90DaySafetyCheckJobId='job2';window.seeds.defectReports=[{id:'defect1',reportNumber:'DR-001',fleetNumber:'M09104',busNumber:'M09104',status:'New',category:'Brakes',safeToDrive:'No',description:'Brake noise',defectDate:new Date().toLocaleDateString('en-CA'),reportedAtIso:new Date().toISOString(),workshopJobId:'job1'}];window.snapshot=name=>({docs:(window.seeds[name]||[]).map(b=>({id:b.id,data:()=>b}))});window.emit=name=>(window.listeners[name]||[]).forEach(cb=>cb(window.snapshot(name)));});
await page.route('**/*',async route=>{const url=new URL(route.request().url());let body,type='text/javascript';
if(url.hostname==='www.gstatic.com')body=mock;
else if(url.pathname==='/js/firebase.js')body='export const db={};export const provider={};export const auth={currentUser:{email:"test@example.com",displayName:"Test User",uid:"test"}};export const storage={};';
else if(url.pathname==='/js/config.js')body='export const ADMIN_EMAILS=["test@example.com"];';
else if(url.pathname==='/js/db.js')body=mockDb;
else {try{body=await fs.readFile(root+url.pathname);if(url.pathname.endsWith('.html'))type='text/html';else if(url.pathname.endsWith('.css'))type='text/css';}catch{return route.fulfill({status:404,body:'missing'})}}
await route.fulfill({body,contentType:type});});
await page.goto('http://workshop.test/'+html);await page.waitForTimeout(1000);
assert.deepEqual(errors,[],html+' initial browser errors');if(html==='workshop.html'){for(const view of ['fleet','odometer','jobs','history','defects','reports','dashboard'])await page.locator('[data-view="'+view+'"]').click();}
await page.evaluate(()=>{window.mutations={};const ids=['fleetTableBody','jobsTableBody','historyList','maintenanceDueList','dashboardJobsList','complianceReportList','complianceFleetStatus','workshopJobReportList','driverDefectReportList','fleetComplianceList','jobQueue','mechanicTodayDefects','workshopDefectList','complianceReportMetrics','workshopJobReportMetrics','fleetComplianceMetrics','driverDefectReportMetrics','historyJobType','historyMechanic','fleetRegisterDepot','fleetRegisterStatus','fleetRegisterFuel','odometerBus','jobBus','odometerHistory'];ids.forEach(id=>{const el=document.getElementById(id);if(!el)return;window.mutations[id]=0;new MutationObserver(records=>window.mutations[id]+=records.length).observe(el,{childList:true,subtree:true});});});
await page.waitForTimeout(500);assert.ok(Object.values(await page.evaluate(()=>window.mutations)).every(n=>n===0),html+' must be idle without an observer loop');
await page.evaluate(()=>{Object.keys(window.mutations).forEach(id=>window.mutations[id]=0);for(let i=0;i<3;i++){window.emit('buses');window.emit('workshopJobs');window.emit('defectReports');}});
await page.waitForTimeout(300);assert.deepEqual(Object.values(await page.evaluate(()=>window.mutations)).filter(n=>n!==0),[],html+' unchanged snapshots must preserve all display roots');
if(html==='workshop.html'){
 await page.locator('[data-view="fleet"]').click();
 const fleetRow=await page.locator('#fleetTableBody tr').first().elementHandle();
 await page.evaluate(()=>{window.seeds.buses[0].vin='UPDATED-VIN';window.seeds.buses[0].notes='Updated vehicle note';window.emit('buses');});await page.waitForTimeout(150);
 assert.equal(await page.locator('[data-optional-cell="vin-chassis"]').innerText(),'UPDATED-VIN');
 assert.equal(await fleetRow.evaluate(el=>el===document.querySelector('#fleetTableBody tr')),true,'Extra field updates preserve existing base row');
 await page.locator('#fleetTableBody tr').first().dblclick();assert.match(await page.locator('#wfBusDialog').innerText(),/Updated vehicle note/);await page.locator('#wfCloseBus').click();
 await page.locator('#fleetSearch').fill('NONEXISTENT');await page.waitForTimeout(100);assert.match(await page.locator('#fleetTableBody').innerText(),/No matching/);await page.locator('#fleetSearch').fill('');await page.waitForTimeout(150);
 assert.equal(await page.locator('#fleetTableBody tr').count(),1);
 await page.evaluate(()=>{window.seeds.buses.push({id:'bus2',fleetNumber:'M09105',status:'Active',depot:'Goulburn',fuelType:'Electric',fireSuppression:'No'});window.emit('buses');});await page.waitForTimeout(150);assert.equal(await page.locator('#fleetTableBody tr').count(),2);
 await page.locator('[data-fleet-sort="fleet"]').click();assert.match(await page.locator('#fleetTableBody tr').first().innerText(),/^M09105/);
 await page.locator('#fleetRegisterDepot').selectOption('Punchbowl');await page.waitForTimeout(150);assert.equal(await page.locator('#fleetTableBody tr:visible').count(),1);await page.evaluate(()=>window.emit('buses'));await page.waitForTimeout(100);assert.equal(await page.locator('#fleetRegisterDepot').inputValue(),'Punchbowl');assert.equal(await page.locator('#fleetTableBody tr:visible').count(),1);await page.locator('#fleetRegisterDepot').selectOption('');
 await page.locator('[data-view="odometer"]').click();await page.locator('#odometerBus').selectOption('bus1');await page.evaluate(()=>{window.seeds.odometerReadings=[{id:'odo1',busId:'bus1',fleetNumber:'M09104',readingDate:'2026-10-07',currentOdometer:123456}];window.emit('odometerReadings');window.emit('buses');});await page.waitForTimeout(100);assert.equal(await page.locator('#odometerBus').inputValue(),'bus1');assert.match(await page.locator('#odometerHistory').innerText(),/123,456/);
 assert.equal(await page.locator('[data-edit-job="job1"]').count(),1);await page.evaluate(()=>{window.seeds.workshopJobs[0].startedAt='2026-10-07T08:00:00Z';window.emit('workshopJobs');});await page.waitForTimeout(100);assert.equal(await page.locator('[data-edit-job="job1"]').count(),0);assert.equal(await page.locator('.job-remove-button').count(),0,'Starting work locks actions even if source row markup is unchanged');await page.evaluate(()=>{window.seeds.workshopJobs[0].status='In Progress';window.emit('workshopJobs');});await page.waitForTimeout(150);
 assert.match(await page.locator('#jobsTableBody').innerText(),/In Progress/);assert.match(await page.locator('#workshopJobReportList').innerText(),/In Progress/);
 await page.locator('[data-view="history"]').click();await page.locator('#historyJobId').fill('NONEXISTENT');assert.equal(await page.locator('#historyList > .list-item:visible').count(),0);
 await page.evaluate(()=>window.emit('workshopJobs'));await page.waitForTimeout(100);assert.equal(await page.locator('#historyJobId').inputValue(),'NONEXISTENT');assert.equal(await page.locator('#historyList > .list-item:visible').count(),0);await page.locator('#historyJobId').fill('');assert.equal(await page.locator('#historyList > .list-item:visible').count(),1);
 await page.locator('[data-view="defects"]').click();await page.locator('[data-defect-notes]').fill('Unsaved operator note');await page.locator('#refreshWorkshopDefects').click();await page.waitForTimeout(100);assert.equal(await page.locator('[data-defect-notes]').inputValue(),'Unsaved operator note');
 await page.locator('[data-view="reports"]').click();await page.locator('[data-report-tab="workshopJobs"]').click();
 await page.evaluate(()=>{window.reviewCalls=0;window.openFleetManagerJobReview=()=>window.reviewCalls++;for(let i=0;i<5;i++)window.emit('workshopJobs');});await page.waitForTimeout(100);await page.locator('[data-workshop-report-view="job1"]').click();assert.equal(await page.evaluate(()=>window.reviewCalls),1,'Repeated renders must not duplicate click handlers');
 await page.locator('#workshopJobReportSearch').fill('NONEXISTENT');assert.match(await page.locator('#workshopJobReportList').innerText(),/No workshop jobs/);await page.locator('#workshopJobReportSearch').fill('');
 await page.locator('[data-report-tab="compliance90"]').click();await page.locator('[data-compliance-view="job2"]').click();assert.equal(await page.locator('#complianceReportDialog').evaluate(el=>el.open),true);await page.locator('#closeComplianceReport').click();
 await page.evaluate(()=>{window.seeds.buses[0].next90DaySafetyCheckDate='2026-11-01';window.emit('buses');});await page.waitForTimeout(100);assert.match(await page.locator('#complianceFleetStatus').innerText(),/01 Nov/);
}else{
 await page.evaluate(()=>{window.seeds.workshopJobs[0].status='In Progress';window.emit('workshopJobs');window.seeds.defectReports[0].description='Updated brake defect';window.emit('defectReports');});await page.waitForTimeout(100);
 assert.match(await page.locator('#jobQueue').innerText(),/In Progress/);assert.match(await page.locator('#mechanicTodayDefects').innerText(),/Updated brake defect/);
 await page.locator('[data-open-job="job1"]').click();await page.locator('#diagnosis').fill('Unsaved mechanic findings');await page.evaluate(()=>{for(let i=0;i<5;i++)window.emit('workshopJobs');});await page.waitForTimeout(100);assert.equal(await page.locator('#diagnosis').inputValue(),'Unsaved mechanic findings');
 await page.locator('#backToQueueBtn').click();await page.locator('#statusFilter').selectOption('Closed');assert.match(await page.locator('#jobQueue').innerText(),/WJ-2026-002/);
}
await page.waitForTimeout(200);await page.evaluate(()=>Object.keys(window.mutations).forEach(id=>window.mutations[id]=0));await page.waitForTimeout(250);assert.ok(Object.values(await page.evaluate(()=>window.mutations)).every(n=>n===0),html+' observers settle after real changes');assert.deepEqual(errors,[]);console.log('PASS '+html+': idle, repeated snapshots, real updates, filters and actions');await page.close();}
await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
