const fs=require('node:fs/promises');const assert=require('node:assert/strict');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root=require('node:path').resolve(__dirname,'../public');
(async()=>{const browser=await chromium.launch({...(process.env.CHROMIUM_PATH ? {executablePath:process.env.CHROMIUM_PATH} : {}),args:['--no-sandbox','--disable-dev-shm-usage'],headless:true});
const page=await browser.newPage({timezoneId:'Australia/Sydney'});const errors=[];page.on('pageerror',e=>errors.push(e.message));
await page.route('**/*',async route=>{const url=new URL(route.request().url());let body,type='text/javascript';
if(url.hostname==='www.gstatic.com')body=`export const collection=(db,name)=>({name});export const onSnapshot=(ref,cb)=>{(window.listeners[ref.name]??=[]).push(cb);cb({docs:(ref.name==='buses'?window.buses:[]).map(b=>({id:b.id,data:()=>b}))});return ()=>{};};export const doc=()=>({});export const serverTimestamp=()=>({});export const setDoc=async()=>{};export const updateDoc=async()=>{};`;
else if(url.pathname==='/js/firebase.js')body='export const db={};export const auth={currentUser:null};';
else if(url.pathname==='/'){type='text/html';body=`<div id="dashboardView"><div class="metrics-grid"></div><section class="panel"><div class="panel-head"><span class="hint">Maintenance due</span></div><div id="maintenanceDueList" class="list-stack"></div></section></div><script>window.listeners={};window.buses=[{id:'1',fleetNumber:'M09104',next90DaySafetyCheckDate:'2026-10-27',last90DaySafetyCheckDate:'2026-07-29',nextFireSuppressionCheckDate:'2026-10-20'}];</script><script type="module">import {renderBaseMaintenance} from '/js/workshop_maintenance_display.js';import '/js/workshop_display_stability.js';import '/js/workshop_90day_tracking.js';import '/js/workshop_special_service_tracking.js';window.renderBase=html=>renderBaseMaintenance(document.getElementById('maintenanceDueList'),html);window.renderBase('');window.emit=()=>window.listeners.buses.forEach(cb=>cb({docs:window.buses.map(b=>({id:b.id,data:()=>b}))}));window.ready=true;</script>`;}
else {try{body=await fs.readFile(root+url.pathname,'utf8')}catch{return route.fulfill({status:404,body:'missing'})}}
await route.fulfill({body,contentType:type});});
await page.goto('http://workshop.test/');await page.waitForFunction(()=>window.ready);await page.waitForTimeout(250);
assert.equal(await page.locator('[data-safety90-dashboard]').count(),1);assert.equal(await page.locator('[data-special-service-dashboard]').count(),1);assert.equal(await page.locator('.empty').count(),0);
await page.evaluate(()=>{window.safetyCard=document.querySelector('[data-safety90-dashboard]');window.specialCard=document.querySelector('[data-special-service-dashboard]');window.mutations=0;new MutationObserver(records=>window.mutations+=records.length).observe(document.getElementById('maintenanceDueList'),{childList:true,subtree:true});for(let i=0;i<20;i++){window.renderBase('');window.emit();}});
await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.mutations),0,'Repeated unchanged snapshots must not repaint maintenance cards');
assert.equal(await page.evaluate(()=>window.safetyCard===document.querySelector('[data-safety90-dashboard]')&&window.specialCard===document.querySelector('[data-special-service-dashboard]')),true);
await page.evaluate(()=>window.renderBase('<div class="list-item">Service due</div>'));assert.equal(await page.locator('.list-item').count(),3);assert.equal(await page.evaluate(()=>window.safetyCard===document.querySelector('[data-safety90-dashboard]')),true);
await page.evaluate(()=>{window.buses[0].last90DaySafetyCheckDate='2026-07-30';window.emit();});await page.waitForTimeout(100);assert.match(await page.locator('[data-safety90-dashboard]').innerText(),/30 July|30 Jul/);
await page.evaluate(()=>{window.buses=[];window.emit();});await page.waitForTimeout(100);assert.equal(await page.locator('.list-item').count(),1);assert.equal(await page.locator('.empty').count(),0);
await page.evaluate(()=>window.renderBase(''));await page.waitForTimeout(100);assert.equal(await page.locator('.empty').count(),1);
await page.evaluate(()=>window.mutations=0);await page.waitForTimeout(250);assert.equal(await page.evaluate(()=>window.mutations),0,'Observers must settle');assert.deepEqual(errors,[]);
console.log('PASS: unchanged snapshots preserve nodes, changed dates refresh, base service and safety/special cards coexist, empty state correct, observers settle.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
